import http.server
import socketserver
import os
import subprocess
import time

# Path to the index.html file
HTML_FILE = 'index.html'

# Function to start a local HTTP server
def start_server():
    Handler = http.server.SimpleHTTPRequestHandler
    with socketserver.TCPServer(("localhost", 0), Handler) as httpd:
        print("Local HTTP server started at port", httpd.server_port)
        print("Server URL: http://localhost:" + str(httpd.server_port))

        # Run ngrok to expose the local server to the internet
        try:
            ngrok_process = subprocess.Popen(['ngrok', 'http', str(httpd.server_port)])
            time.sleep(2)  # Wait a bit for ngrok to start
            ngrok_process.wait()
        except FileNotFoundError:
            print("Ngrok not found. Please install ngrok or use another tool to expose your local server.")

if __name__ == "__main__":
    # Save the HTML content to index.html
    with open(HTML_FILE, 'w', encoding='utf-8') as f:
        f.write("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Static Page</title>
</head>
<body>
    <h1>Hello, World!</h1>
    <p>This is a basic static web page generated by Python.</p>
</body>
</html>""")
    
    # Start the local server and expose it with ngrok
    start_server()
