name: 自动监控斗鱼

on:
  workflow_dispatch:
    inputs:
      user_message:
        description: '房间号'
        required: true
        default: '292098'
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-douyu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pytz

      - name: 自动监控斗鱼
        run: python douyu.py ${{ github.event.inputs.user_message }}
        shell: bash

      - name: Commit douyu.txt
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add douyu.txt
          git commit -m "Update douyu.txt with the latest status"
          git push
